### ISSUE TITLE
Possible to limit number of time a tile is used ?

### ISSUE THREAD

**Issue by ludov04** [codebox/mosaic#1]
Hi, 
your tool seems very useful, I have one simple question:

Is it possible to limit the number of time a tile is used ?
If yes, how can it be achieved ?
If no, is it easily implementable, any idea how to implement it ?

Thank you .

**Comment by codebox** [comment]
Hi,
There is no way to do this at the moment, but it shouldn't be too difficult
to achieve. If you make a change to the TileFitter class to keep a count of
how many times each tile gets used, and then remove any tile that gets used
more than a certain number of times that should give you what you need.
Rob

**Comment by ludov04** [comment]
Ok great, I'll try that.
Another question: 
I'm not familiar with multiprocessing in python, but as I understand, there is one instance of TileFitter per worker. So if I really want an absolute limit, I have to create some shared state across thoses instances to keep count of how many times a tile gets used. Am I right ? Is there another solution to avoid shared state, as it is not really recommended ?
Ludovic

**Comment by codebox** [comment]
Yes, that's correct you get one TileFitter per worker - I would suggest
giving a limit to each TileFitter individually rather than having one
shared limit value, eg if you are using 4 CPU cores and want each tile to
be used at most 100 times set the limit for each TileFitter to be 25.
