### ISSUE TITLE
invalid path issue

### ISSUE THREAD

**Issue by Phrynobatrachus** [codebox/mosaic#3]
Hey, I'm trying to run this, and can't seem to get the tiles to be recognized in the command. I have a subdirectory called 'screens' from where the .py file is

python mosaic.py imgSrc screens
python mosaic.py imgSrc /screens
python mosaic.py imgSrc fullPath

all give me 

invalid syntax

Am I missing something obvious here?

**Comment by codebox** [comment]
Can you let me know the exact command you are running, and the full output that you get (maybe a screenshot?) also, what OS and python version are you using

**Comment by Phrynobatrachus** [comment]
![image](https://cloud.githubusercontent.com/assets/3723666/18967826/bb06044a-8654-11e6-980b-74fdc337ad34.png)

Fresh install of Python 3.5.

**Comment by codebox** [comment]
Ok, that explains it - you are using Python 3 and the code in this project is intended for Python 2. You can have both versions installed on your PC together, just make sure you use the right one when you run the code.

**Comment by Phrynobatrachus** [comment]
Thanks!
