### ISSUE TITLE
Weird Error trying to run Mosaic

### ISSUE THREAD

**Issue by Luka1745** [codebox/mosaic#9]
I've got this weird problem when trying to run it. Here is the copy from the terminal. I've had it running for a couple of hours and it doesn't change no matter the time running 

python mosaic.py GLAM.jpg /home/rogue/Videos/'LTT Glam'
Reading tiles from '/home/rogue/Videos/LTT Glam'...
Processed 0 tiles.
Processing main image...
Main image processed.
Building mosaic, press Ctrl-C to abort...
Progress: Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "mosaic.py", line 166, in build_mosaic
    tile_data = all_tile_data_large[best_fit_tile_index]
TypeError: list indices must be integers, not NoneType
Progress: 99%

**Comment by codebox** [comment]
I think the problem is that the app did not find your tile images (see the 'Processed 0 tiles.' message) The problem is probably due to the quotes you put around the final part of the path, try '/home/rogue/Videos/LTT Glam' instead of /home/rogue/Videos/'LTT Glam'
